name: build macOS

on: [workflow_dispatch]

jobs:
  build_macos:
    name: ${{ matrix.os }}/node-${{ matrix.node-version }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node-version: [12.x]
        os: [macOS-latest]
    steps:
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - uses: actions/checkout@v2

      - name: Install esy
        run: |
          npm install -g esy

      - name: Install and build
        run: esy

      - name: Copy built PPX file
        run: |
          mv ./_build/install/default/bin/esy esy

      - name: (only on release) Upload artifacts ${{ matrix.os }}
        uses: actions/upload-artifact@master
        with:
          name: ${{ matrix.os }}
          path: esy
          if-no-files-found: error
